global:
  scrape_interval: 30s

scrape_configs:
  - job_name: "envoy"
    scrape_interval: 5s
    metrics_path: /stats/prometheus
    static_configs:
      - targets: [ 'envoy:9901' ]
  - job_name: node
    scrape_interval: 5s
    static_configs:
      - targets: ['node-exporter:9100']
  - job_name: highload1
    scrape_interval: 5s
    static_configs:
      - targets: ['highload3_1:5000']
  - job_name: highload2
    scrape_interval: 5s
    static_configs:
      - targets: ['highload3_2:5000']
  - job_name: highload3
    scrape_interval: 5s
    static_configs:
      - targets: ['highload3_3:5000']
